# Generated by Django 4.1 on 2022-09-02 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places_api', '0002_category_place_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
    ]
