# Generated by Django 4.1 on 2022-09-03 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places_api', '0003_rename_category_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgplace',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places_api.place'),
        ),
    ]
